### ISSUE TITLE
Provide command line flag supporting summary figure output.

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/fraisty#37]
The bin script should accept an optional flag specifying the directory in which to output the `fraisty_summary.png` figure.

e.g.  `bin/fraisty.sh --data mydata.csv --spek myspek.json --fig-dir foo`

Accept `--fig-dir` or `-f`

## Todos
- [x] add flag to help content for script
- [x] add flag to options parsing
- [x] store value in variable
